[package]
name = "environment"
version = "0.1.0"
authors = ["Adrien Bennadji <adrien.bennadji@live.fr>"]
edition = "2018"

[dependencies]
vulkan = { path = "../vulkan" }
util = { path = "../util" }
math = { path = "../math" }

log = "0.4"
env_logger = "0.8"
