[package]
name = "math"
version = "0.1.0"
authors = ["Adrien Bennadji <adrien.bennadji@live.fr>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.8"
cgmath = "0.18"
rand = "0.8"
lerp = "0.4"
